# application.properties --> dosyasinda asagidaki gibi yazilir.
# server.port=9090
# TODO: Dikkat, burada key-value çalismalarinda anahtar: bilgisinden sonra deger, bir boşluk birakilarak yazilmalidir.
# server:
#   port:9090 --> iki noktaya bitisik deger yazimi yanlistir.
# server:
# port: 9090 --> port degeri server'in alt basligidir bu nedenle ayni hizada degil bir tab içeride yazilmali
server:
  port: 9090

# application.properties dosyasında aşağıdaki gibi kullanılır.
# spring.datasource.url
# spring.datasource.username
# spring.datasource.password
# spring.datasource.driver-class-name

# application.yml dosyasında aşağıdaki gibi kullanılır. Alt başlıklar bir tab içeride olacak şekilde.
spring:
  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: ""
